language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    #- platform-tools
    - build-tools-24.0.3
    - android-24
    - extra-android-support
    - extra-android-m2repository

before_install:
 - chmod +x gradlew

script:
   - chmod +x ./gradlew
   - ./gradlew build connectedCheck
